### ISSUE TITLE
Unable to load without Collaborator

### ISSUE THREAD

**Issue by rewardone** [GovTech-CSG/Autowasp#8]
**Perceived Issue**: Autowasp is unable to be loaded without Collaborator

**Burp Version**: Professional v2021.3.1
**Error message**: 
`java.lang.IllegalStateException: Burp Collaborator is disabled in the Project options
	at burp.b8i.a(Unknown Source)
	at burp.b8i.generatePayload(Unknown Source)
	at burp.aq8.generatePayload(Unknown Source)
	at autowasp.logger.TrafficLogic.<init>(TrafficLogic.java:69)
	at autowasp.Autowasp.registerExtenderCallbacks(Autowasp.java:98)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at burp.bza.lambda$registerExtenderCallbacks$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
`

[Needing Collaborator for some features is known via Dev response](https://github.com/GovTech-CSG/Autowasp/issues/7#issuecomment-809044468)

**Desired/Expected State**: Able to load and use Autowasp without Collaborator

**Comment by imthomas93** [comment]
Hello, can i check if you are using Burp Community version?

**Comment by rewardone** [comment]
> Hello, can i check if you are using Burp Community version?

I am not using Community. Using the latest version of Professional, 2021.3.1

I am using project preferences to launch Burp with Collaborator disabled.

**Comment by imthomas93** [comment]
Hi @rewardone,

Thanks for your feedback.

Noted that your project preferences is to launch Burp with Collaborator disabled. Our current implementation with one of our test case require the use of Burp Collaborator. 

We are checking out with PortSwigger to see if there are any workaround and will support Burp Community and BurpSuite Pro with collaborator feature disabled. 

@imthomas93
